### ISSUE TITLE
Order of steps for the workflow

### ISSUE THREAD

**Issue by cjsifuen** [ndcn/infer-subc-2D#24]
What is the correct order of the steps in the analysis, or does it matter? The documentation and linked output seem a bit confusing.

@ergonyc or @shanrhoads -- you have a much better handle on this than I do.

**Comment by shanrhoads** [comment]
Hello! 
The notebooks illustrate the suggested order of steps. Each one walks you through the thought process we used to create the segmentation for that cellular structure. To elaborate a bit, we are analyzing multichannel images in which 6 different organelle are labeled. In the suggested workflow, we first identifying a single cell of interest (notebooks 01-03), then segment each of the organelles from separate channels of the raw image (notebooks 04-09). However, a lot of the steps can act completely independent of each other. For example, if an image only contained staining for mitochondria, functions created in 05_infer_mitochondria could be used to segment that image.

Hope that helps!
Shannon

**Comment by cjsifuen** [comment]
Hi Shannon!

Yes, that helps a lot. I think we should update the documentation a bit to incorporate this. I'll create a branch to update the README. I'll focus on making it more approachable from an outsider point of view, if that's okay. 

I'll then submit it for review and merging.

Does that sound good @shanrhoads and @ergonyc ?

**Comment by shanrhoads** [comment]
That sounds great. Thanks!
